// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * DBInstance is the Schema for the DBInstances API
 *
 * @schema DBInstance
 */
export class DbInstance extends ApiObject {
  /**
   * Returns the apiVersion and kind for "DBInstance"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'rds.services.k8s.aws/v1alpha1',
    kind: 'DBInstance',
  }

  /**
   * Renders a Kubernetes manifest for "DBInstance".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: DbInstanceProps = {}): any {
    return {
      ...DbInstance.GVK,
      ...toJson_DbInstanceProps(props),
    };
  }

  /**
   * Defines a "DBInstance" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: DbInstanceProps = {}) {
    super(scope, id, {
      ...DbInstance.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...DbInstance.GVK,
      ...toJson_DbInstanceProps(resolved),
    };
  }
}

/**
 * DBInstance is the Schema for the DBInstances API
 *
 * @schema DBInstance
 */
export interface DbInstanceProps {
  /**
   * @schema DBInstance#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * DBInstanceSpec defines the desired state of DBInstance.
   * Contains the details of an Amazon RDS DB instance.
   * This data type is used as a response element in the DescribeDBInstances action.
   *
   * @schema DBInstance#spec
   */
  readonly spec?: DbInstanceSpec;

}

/**
 * Converts an object of type 'DbInstanceProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DbInstanceProps(obj: DbInstanceProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_DbInstanceSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * DBInstanceSpec defines the desired state of DBInstance.
 * Contains the details of an Amazon RDS DB instance.
 * This data type is used as a response element in the DescribeDBInstances action.
 *
 * @schema DbInstanceSpec
 */
export interface DbInstanceSpec {
  /**
   * The amount of storage in gibibytes (GiB) to allocate for the DB instance.
   * Type: Integer
   * Amazon Aurora
   * Not applicable. Aurora cluster volumes automatically grow as the amount of data in your database increases, though you are only charged for the space that you use in an Aurora cluster volume.
   * Amazon RDS Custom
   * Constraints to the amount of storage for each storage type are the following:
   * * General Purpose (SSD) storage (gp2): Must be an integer from 40 to 65536.
   * * Provisioned IOPS storage (io1): Must be an integer from 40 to 65536.
   * MySQL
   * Constraints to the amount of storage for each storage type are the following:
   * * General Purpose (SSD) storage (gp2): Must be an integer from 20 to 65536.
   * * Provisioned IOPS storage (io1): Must be an integer from 100 to 65536.
   * * Magnetic storage (standard): Must be an integer from 5 to 3072.
   * MariaDB
   * Constraints to the amount of storage for each storage type are the following:
   * * General Purpose (SSD) storage (gp2): Must be an integer from 20 to 65536.
   * * Provisioned IOPS storage (io1): Must be an integer from 100 to 65536.
   * * Magnetic storage (standard): Must be an integer from 5 to 3072.
   * PostgreSQL
   * Constraints to the amount of storage for each storage type are the following:
   * * General Purpose (SSD) storage (gp2): Must be an integer from 20 to 65536.
   * * Provisioned IOPS storage (io1): Must be an integer from 100 to 65536.
   * * Magnetic storage (standard): Must be an integer from 5 to 3072.
   * Oracle
   * Constraints to the amount of storage for each storage type are the following:
   * * General Purpose (SSD) storage (gp2): Must be an integer from 20 to 65536.
   * * Provisioned IOPS storage (io1): Must be an integer from 100 to 65536.
   * * Magnetic storage (standard): Must be an integer from 10 to 3072.
   * SQL Server
   * Constraints to the amount of storage for each storage type are the following:
   * * General Purpose (SSD) storage (gp2): Enterprise and Standard editions:    Must be an integer from 200 to 16384. Web and Express editions: Must be    an integer from 20 to 16384.
   * * Provisioned IOPS storage (io1): Enterprise and Standard editions: Must    be an integer from 200 to 16384. Web and Express editions: Must be an    integer from 100 to 16384.
   * * Magnetic storage (standard): Enterprise and Standard editions: Must    be an integer from 200 to 1024. Web and Express editions: Must be an integer    from 20 to 1024.
   *
   * @schema DbInstanceSpec#allocatedStorage
   */
  readonly allocatedStorage?: number;

  /**
   * A value that indicates whether minor engine upgrades are applied automatically to the DB instance during the maintenance window. By default, minor engine upgrades are applied automatically.
   * If you create an RDS Custom DB instance, you must set AutoMinorVersionUpgrade to false.
   *
   * @schema DbInstanceSpec#autoMinorVersionUpgrade
   */
  readonly autoMinorVersionUpgrade?: boolean;

  /**
   * The Availability Zone (AZ) where the database will be created. For information on Amazon Web Services Regions and Availability Zones, see Regions and Availability Zones (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html).
   * Default: A random, system-chosen Availability Zone in the endpoint's Amazon Web Services Region.
   * Example: us-east-1d
   * Constraint: The AvailabilityZone parameter can't be specified if the DB instance is a Multi-AZ deployment. The specified Availability Zone must be in the same Amazon Web Services Region as the current endpoint.
   * If you're creating a DB instance in an RDS on VMware environment, specify the identifier of the custom Availability Zone to create the DB instance in.
   * For more information about RDS on VMware, see the RDS on VMware User Guide. (https://docs.aws.amazon.com/AmazonRDS/latest/RDSonVMwareUserGuide/rds-on-vmware.html)
   *
   * @schema DbInstanceSpec#availabilityZone
   */
  readonly availabilityZone?: string;

  /**
   * The number of days for which automated backups are retained. Setting this parameter to a positive number enables backups. Setting this parameter to 0 disables automated backups.
   * Amazon Aurora
   * Not applicable. The retention period for automated backups is managed by the DB cluster.
   * Default: 1
   * Constraints:
   * * Must be a value from 0 to 35
   * * Can't be set to 0 if the DB instance is a source to read replicas
   * * Can't be set to 0 or 35 for an RDS Custom DB instance
   *
   * @schema DbInstanceSpec#backupRetentionPeriod
   */
  readonly backupRetentionPeriod?: number;

  /**
   * For supported engines, this value indicates that the DB instance should be associated with the specified CharacterSet.
   * This setting doesn't apply to RDS Custom. However, if you need to change the character set, you can change it on the database itself.
   * Amazon Aurora
   * Not applicable. The character set is managed by the DB cluster. For more information, see CreateDBCluster.
   *
   * @schema DbInstanceSpec#characterSetName
   */
  readonly characterSetName?: string;

  /**
   * A value that indicates whether to copy tags from the DB instance to snapshots of the DB instance. By default, tags are not copied.
   * Amazon Aurora
   * Not applicable. Copying tags to snapshots is managed by the DB cluster. Setting this value for an Aurora DB instance has no effect on the DB cluster setting.
   *
   * @schema DbInstanceSpec#copyTagsToSnapshot
   */
  readonly copyTagsToSnapshot?: boolean;

  /**
   * The instance profile associated with the underlying Amazon EC2 instance of an RDS Custom DB instance. The instance profile must meet the following requirements:
   * * The profile must exist in your account.
   * * The profile must have an IAM role that Amazon EC2 has permissions to    assume.
   * * The instance profile name and the associated IAM role name must start    with the prefix AWSRDSCustom.
   * For the list of permissions required for the IAM role, see Configure IAM and your VPC (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/custom-setup-orcl.html#custom-setup-orcl.iam-vpc) in the Amazon Relational Database Service User Guide.
   * This setting is required for RDS Custom.
   *
   * @schema DbInstanceSpec#customIAMInstanceProfile
   */
  readonly customIamInstanceProfile?: string;

  /**
   * The identifier of the DB cluster that the instance will belong to.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#dbClusterIdentifier
   */
  readonly dbClusterIdentifier?: string;

  /**
   * The compute and memory capacity of the DB instance, for example, db.m4.large. Not all DB instance classes are available in all Amazon Web Services Regions, or for all database engines. For the full list of DB instance classes, and availability for your engine, see DB Instance Class (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html) in the Amazon RDS User Guide.
   *
   * @schema DbInstanceSpec#dbInstanceClass
   */
  readonly dbInstanceClass: string;

  /**
   * The DB instance identifier. This parameter is stored as a lowercase string.
   * Constraints:
   * * Must contain from 1 to 63 letters, numbers, or hyphens.
   * * First character must be a letter.
   * * Can't end with a hyphen or contain two consecutive hyphens.
   * Example: mydbinstance
   *
   * @schema DbInstanceSpec#dbInstanceIdentifier
   */
  readonly dbInstanceIdentifier: string;

  /**
   * The meaning of this parameter differs according to the database engine you use.
   * MySQL
   * The name of the database to create when the DB instance is created. If this parameter isn't specified, no database is created in the DB instance.
   * Constraints:
   * * Must contain 1 to 64 letters or numbers.
   * * Must begin with a letter. Subsequent characters can be letters, underscores,    or digits (0-9).
   * * Can't be a word reserved by the specified database engine
   * MariaDB
   * The name of the database to create when the DB instance is created. If this parameter isn't specified, no database is created in the DB instance.
   * Constraints:
   * * Must contain 1 to 64 letters or numbers.
   * * Must begin with a letter. Subsequent characters can be letters, underscores,    or digits (0-9).
   * * Can't be a word reserved by the specified database engine
   * PostgreSQL
   * The name of the database to create when the DB instance is created. If this parameter isn't specified, a database named postgres is created in the DB instance.
   * Constraints:
   * * Must contain 1 to 63 letters, numbers, or underscores.
   * * Must begin with a letter. Subsequent characters can be letters, underscores,    or digits (0-9).
   * * Can't be a word reserved by the specified database engine
   * Oracle
   * The Oracle System ID (SID) of the created DB instance. If you specify null, the default value ORCL is used. You can't specify the string NULL, or any other reserved word, for DBName.
   * Default: ORCL
   * Constraints:
   * * Can't be longer than 8 characters
   * Amazon RDS Custom
   * The Oracle System ID (SID) of the created RDS Custom DB instance. If you don't specify a value, the default value is ORCL.
   * Default: ORCL
   * Constraints:
   * * It must contain 1 to 8 alphanumeric characters.
   * * It must contain a letter.
   * * It can't be a word reserved by the database engine.
   * SQL Server
   * Not applicable. Must be null.
   * Amazon Aurora MySQL
   * The name of the database to create when the primary DB instance of the Aurora MySQL DB cluster is created. If this parameter isn't specified for an Aurora MySQL DB cluster, no database is created in the DB cluster.
   * Constraints:
   * * It must contain 1 to 64 alphanumeric characters.
   * * It can't be a word reserved by the database engine.
   * Amazon Aurora PostgreSQL
   * The name of the database to create when the primary DB instance of the Aurora PostgreSQL DB cluster is created. If this parameter isn't specified for an Aurora PostgreSQL DB cluster, a database named postgres is created in the DB cluster.
   * Constraints:
   * * It must contain 1 to 63 alphanumeric characters.
   * * It must begin with a letter or an underscore. Subsequent characters    can be letters, underscores, or digits (0 to 9).
   * * It can't be a word reserved by the database engine.
   *
   * @schema DbInstanceSpec#dbName
   */
  readonly dbName?: string;

  /**
   * The name of the DB parameter group to associate with this DB instance. If you do not specify a value, then the default DB parameter group for the specified DB engine and version is used.
   * This setting doesn't apply to RDS Custom.
   * Constraints:
   * * Must be 1 to 255 letters, numbers, or hyphens.
   * * First character must be a letter
   * * Can't end with a hyphen or contain two consecutive hyphens
   *
   * @schema DbInstanceSpec#dbParameterGroupName
   */
  readonly dbParameterGroupName?: string;

  /**
   * A list of DB security groups to associate with this DB instance.
   * Default: The default DB security group for the database engine.
   *
   * @schema DbInstanceSpec#dbSecurityGroups
   */
  readonly dbSecurityGroups?: string[];

  /**
   * A DB subnet group to associate with this DB instance.
   * If there is no DB subnet group, then it is a non-VPC DB instance.
   *
   * @schema DbInstanceSpec#dbSubnetGroupName
   */
  readonly dbSubnetGroupName?: string;

  /**
   * A value that indicates whether the DB instance has deletion protection enabled. The database can't be deleted when deletion protection is enabled. By default, deletion protection is disabled. For more information, see Deleting a DB Instance (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_DeleteInstance.html).
   * Amazon Aurora
   * Not applicable. You can enable or disable deletion protection for the DB cluster. For more information, see CreateDBCluster. DB instances in a DB cluster can be deleted even when deletion protection is enabled for the DB cluster.
   *
   * @schema DbInstanceSpec#deletionProtection
   */
  readonly deletionProtection?: boolean;

  /**
   * The Active Directory directory ID to create the DB instance in. Currently, only MySQL, Microsoft SQL Server, Oracle, and PostgreSQL DB instances can be created in an Active Directory Domain.
   * For more information, see Kerberos Authentication (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/kerberos-authentication.html) in the Amazon RDS User Guide.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#domain
   */
  readonly domain?: string;

  /**
   * Specify the name of the IAM role to be used when making API calls to the Directory Service.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#domainIAMRoleName
   */
  readonly domainIamRoleName?: string;

  /**
   * The list of log types that need to be enabled for exporting to CloudWatch Logs. The values in the list depend on the DB engine. For more information, see Publishing Database Logs to Amazon CloudWatch Logs (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.html#USER_LogAccess.Procedural.UploadtoCloudWatch) in the Amazon Relational Database Service User Guide.
   * Amazon Aurora
   * Not applicable. CloudWatch Logs exports are managed by the DB cluster.
   * RDS Custom
   * Not applicable.
   * MariaDB
   * Possible values are audit, error, general, and slowquery.
   * Microsoft SQL Server
   * Possible values are agent and error.
   * MySQL
   * Possible values are audit, error, general, and slowquery.
   * Oracle
   * Possible values are alert, audit, listener, trace, and oemagent.
   * PostgreSQL
   * Possible values are postgresql and upgrade.
   *
   * @schema DbInstanceSpec#enableCloudwatchLogsExports
   */
  readonly enableCloudwatchLogsExports?: string[];

  /**
   * A value that indicates whether to enable a customer-owned IP address (CoIP) for an RDS on Outposts DB instance.
   * A CoIP provides local or external connectivity to resources in your Outpost subnets through your on-premises network. For some use cases, a CoIP can provide lower latency for connections to the DB instance from outside of its virtual private cloud (VPC) on your local network.
   * For more information about RDS on Outposts, see Working with Amazon RDS on Amazon Web Services Outposts (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-on-outposts.html) in the Amazon RDS User Guide.
   * For more information about CoIPs, see Customer-owned IP addresses (https://docs.aws.amazon.com/outposts/latest/userguide/outposts-networking-components.html#ip-addressing) in the Amazon Web Services Outposts User Guide.
   *
   * @schema DbInstanceSpec#enableCustomerOwnedIP
   */
  readonly enableCustomerOwnedIp?: boolean;

  /**
   * A value that indicates whether to enable mapping of Amazon Web Services Identity and Access Management (IAM) accounts to database accounts. By default, mapping is disabled.
   * This setting doesn't apply to RDS Custom or Amazon Aurora. In Aurora, mapping Amazon Web Services IAM accounts to database accounts is managed by the DB cluster.
   * For more information, see IAM Database Authentication for MySQL and PostgreSQL (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html) in the Amazon RDS User Guide.
   *
   * @schema DbInstanceSpec#enableIAMDatabaseAuthentication
   */
  readonly enableIamDatabaseAuthentication?: boolean;

  /**
   * The name of the database engine to be used for this instance.
   * Not every database engine is available for every Amazon Web Services Region.
   * Valid Values:
   * * aurora (for MySQL 5.6-compatible Aurora)
   * * aurora-mysql (for MySQL 5.7-compatible Aurora)
   * * aurora-postgresql
   * * custom-oracle-ee (for RDS Custom instances)
   * * mariadb
   * * mysql
   * * oracle-ee
   * * oracle-ee-cdb
   * * oracle-se2
   * * oracle-se2-cdb
   * * postgres
   * * sqlserver-ee
   * * sqlserver-se
   * * sqlserver-ex
   * * sqlserver-web
   *
   * @schema DbInstanceSpec#engine
   */
  readonly engine: string;

  /**
   * The version number of the database engine to use.
   * For a list of valid engine versions, use the DescribeDBEngineVersions action.
   * The following are the database engines and links to information about the major and minor versions that are available with Amazon RDS. Not every database engine is available for every Amazon Web Services Region.
   * Amazon Aurora
   * Not applicable. The version number of the database engine to be used by the DB instance is managed by the DB cluster.
   * Amazon RDS Custom
   * A custom engine version (CEV) that you have previously created. This setting is required for RDS Custom. The CEV name has the following format: 19.customized_string . An example identifier is 19.my_cev1. For more information, see Creating an RDS Custom DB instance (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/custom-creating.html#custom-creating.create) in the Amazon RDS User Guide..
   * MariaDB
   * See MariaDB on Amazon RDS Versions (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MariaDB.html#MariaDB.Concepts.VersionMgmt) in the Amazon RDS User Guide.
   * Microsoft SQL Server
   * See Microsoft SQL Server Versions on Amazon RDS (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html#SQLServer.Concepts.General.VersionSupport) in the Amazon RDS User Guide.
   * MySQL
   * See MySQL on Amazon RDS Versions (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt) in the Amazon RDS User Guide.
   * Oracle
   * See Oracle Database Engine Release Notes (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.Oracle.PatchComposition.html) in the Amazon RDS User Guide.
   * PostgreSQL
   * See Amazon RDS for PostgreSQL versions and extensions (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts) in the Amazon RDS User Guide.
   *
   * @schema DbInstanceSpec#engineVersion
   */
  readonly engineVersion?: string;

  /**
   * The amount of Provisioned IOPS (input/output operations per second) to be initially allocated for the DB instance. For information about valid Iops values, see Amazon RDS Provisioned IOPS Storage to Improve Performance (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#USER_PIOPS) in the Amazon RDS User Guide.
   * Constraints: For MariaDB, MySQL, Oracle, and PostgreSQL DB instances, must be a multiple between .5 and 50 of the storage amount for the DB instance. For SQL Server DB instances, must be a multiple between 1 and 50 of the storage amount for the DB instance.
   *
   * @schema DbInstanceSpec#iops
   */
  readonly iops?: number;

  /**
   * The Amazon Web Services KMS key identifier for an encrypted DB instance.
   * The Amazon Web Services KMS key identifier is the key ARN, key ID, alias ARN, or alias name for the KMS key. To use a KMS key in a different Amazon Web Services account, specify the key ARN or alias ARN.
   * Amazon Aurora
   * Not applicable. The Amazon Web Services KMS key identifier is managed by the DB cluster. For more information, see CreateDBCluster.
   * If StorageEncrypted is enabled, and you do not specify a value for the KmsKeyId parameter, then Amazon RDS uses your default KMS key. There is a default KMS key for your Amazon Web Services account. Your Amazon Web Services account has a different default KMS key for each Amazon Web Services Region.
   * Amazon RDS Custom
   * A KMS key is required for RDS Custom Oracle instances. For most RDS engines, if you leave this parameter empty while enabling StorageEncrypted, the engine uses the default KMS key. However, RDS Custom for Oracle doesn't use the default key when this parameter is empty. You must explicitly specify a key.
   *
   * @schema DbInstanceSpec#kmsKeyID
   */
  readonly kmsKeyId?: string;

  /**
   * AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference type to provide more user friendly syntax for references using 'from' field Ex: APIIDRef:   from:     name: my-api
   *
   * @schema DbInstanceSpec#kmsKeyRef
   */
  readonly kmsKeyRef?: DbInstanceSpecKmsKeyRef;

  /**
   * License model information for this DB instance.
   * Valid values: license-included | bring-your-own-license | general-public-license
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#licenseModel
   */
  readonly licenseModel?: string;

  /**
   * The password for the master user. The password can include any printable ASCII character except "/", """, or "@".
   * Amazon Aurora
   * Not applicable. The password for the master user is managed by the DB cluster.
   * MariaDB
   * Constraints: Must contain from 8 to 41 characters.
   * Microsoft SQL Server
   * Constraints: Must contain from 8 to 128 characters.
   * MySQL
   * Constraints: Must contain from 8 to 41 characters.
   * Oracle
   * Constraints: Must contain from 8 to 30 characters.
   * PostgreSQL
   * Constraints: Must contain from 8 to 128 characters.
   *
   * @schema DbInstanceSpec#masterUserPassword
   */
  readonly masterUserPassword?: DbInstanceSpecMasterUserPassword;

  /**
   * The name for the master user.
   * Amazon Aurora
   * Not applicable. The name for the master user is managed by the DB cluster.
   * MariaDB
   * Constraints:
   * * Required for MariaDB.
   * * Must be 1 to 16 letters or numbers.
   * * Can't be a reserved word for the chosen database engine.
   * Microsoft SQL Server
   * Constraints:
   * * Required for SQL Server.
   * * Must be 1 to 128 letters or numbers.
   * * The first character must be a letter.
   * * Can't be a reserved word for the chosen database engine.
   * MySQL
   * Constraints:
   * * Required for MySQL.
   * * Must be 1 to 16 letters or numbers.
   * * First character must be a letter.
   * * Can't be a reserved word for the chosen database engine.
   * Oracle
   * Constraints:
   * * Required for Oracle.
   * * Must be 1 to 30 letters or numbers.
   * * First character must be a letter.
   * * Can't be a reserved word for the chosen database engine.
   * PostgreSQL
   * Constraints:
   * * Required for PostgreSQL.
   * * Must be 1 to 63 letters or numbers.
   * * First character must be a letter.
   * * Can't be a reserved word for the chosen database engine.
   *
   * @schema DbInstanceSpec#masterUsername
   */
  readonly masterUsername?: string;

  /**
   * The upper limit in gibibytes (GiB) to which Amazon RDS can automatically scale the storage of the DB instance.
   * For more information about this setting, including limitations that apply to it, see Managing capacity automatically with Amazon RDS storage autoscaling (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIOPS.StorageTypes.html#USER_PIOPS.Autoscaling) in the Amazon RDS User Guide.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#maxAllocatedStorage
   */
  readonly maxAllocatedStorage?: number;

  /**
   * The interval, in seconds, between points when Enhanced Monitoring metrics are collected for the DB instance. To disable collection of Enhanced Monitoring metrics, specify 0. The default is 0.
   * If MonitoringRoleArn is specified, then you must set MonitoringInterval to a value other than 0.
   * This setting doesn't apply to RDS Custom.
   * Valid Values: 0, 1, 5, 10, 15, 30, 60
   *
   * @schema DbInstanceSpec#monitoringInterval
   */
  readonly monitoringInterval?: number;

  /**
   * The ARN for the IAM role that permits RDS to send enhanced monitoring metrics to Amazon CloudWatch Logs. For example, arn:aws:iam:123456789012:role/emaccess. For information on creating a monitoring role, see Setting Up and Enabling Enhanced Monitoring (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.html#USER_Monitoring.OS.Enabling) in the Amazon RDS User Guide.
   * If MonitoringInterval is set to a value other than 0, then you must supply a MonitoringRoleArn value.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#monitoringRoleARN
   */
  readonly monitoringRoleArn?: string;

  /**
   * A value that indicates whether the DB instance is a Multi-AZ deployment. You can't set the AvailabilityZone parameter if the DB instance is a Multi-AZ deployment.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#multiAZ
   */
  readonly multiAz?: boolean;

  /**
   * The name of the NCHAR character set for the Oracle DB instance.
   * This parameter doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#ncharCharacterSetName
   */
  readonly ncharCharacterSetName?: string;

  /**
   * A value that indicates that the DB instance should be associated with the specified option group.
   * Permanent options, such as the TDE option for Oracle Advanced Security TDE, can't be removed from an option group. Also, that option group can't be removed from a DB instance after it is associated with a DB instance.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#optionGroupName
   */
  readonly optionGroupName?: string;

  /**
   * A value that indicates whether to enable Performance Insights for the DB instance. For more information, see Using Amazon Performance Insights (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.html) in the Amazon Relational Database Service User Guide.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#performanceInsightsEnabled
   */
  readonly performanceInsightsEnabled?: boolean;

  /**
   * The Amazon Web Services KMS key identifier for encryption of Performance Insights data.
   * The Amazon Web Services KMS key identifier is the key ARN, key ID, alias ARN, or alias name for the KMS key.
   * If you do not specify a value for PerformanceInsightsKMSKeyId, then Amazon RDS uses your default KMS key. There is a default KMS key for your Amazon Web Services account. Your Amazon Web Services account has a different default KMS key for each Amazon Web Services Region.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#performanceInsightsKMSKeyID
   */
  readonly performanceInsightsKmsKeyId?: string;

  /**
   * The amount of time, in days, to retain Performance Insights data. Valid values are 7 or 731 (2 years).
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#performanceInsightsRetentionPeriod
   */
  readonly performanceInsightsRetentionPeriod?: number;

  /**
   * The port number on which the database accepts connections.
   * MySQL
   * Default: 3306
   * Valid values: 1150-65535
   * Type: Integer
   * MariaDB
   * Default: 3306
   * Valid values: 1150-65535
   * Type: Integer
   * PostgreSQL
   * Default: 5432
   * Valid values: 1150-65535
   * Type: Integer
   * Oracle
   * Default: 1521
   * Valid values: 1150-65535
   * SQL Server
   * Default: 1433
   * Valid values: 1150-65535 except 1234, 1434, 3260, 3343, 3389, 47001, and 49152-49156.
   * Amazon Aurora
   * Default: 3306
   * Valid values: 1150-65535
   * Type: Integer
   *
   * @schema DbInstanceSpec#port
   */
  readonly port?: number;

  /**
   * The daily time range during which automated backups are created if automated backups are enabled, using the BackupRetentionPeriod parameter. The default is a 30-minute window selected at random from an 8-hour block of time for each Amazon Web Services Region. For more information, see Backup window (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html#USER_WorkingWithAutomatedBackups.BackupWindow) in the Amazon RDS User Guide.
   * Amazon Aurora
   * Not applicable. The daily time range for creating automated backups is managed by the DB cluster.
   * Constraints:
   * * Must be in the format hh24:mi-hh24:mi.
   * * Must be in Universal Coordinated Time (UTC).
   * * Must not conflict with the preferred maintenance window.
   * * Must be at least 30 minutes.
   *
   * @schema DbInstanceSpec#preferredBackupWindow
   */
  readonly preferredBackupWindow?: string;

  /**
   * The time range each week during which system maintenance can occur, in Universal Coordinated Time (UTC). For more information, see Amazon RDS Maintenance Window (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html#Concepts.DBMaintenance).
   * Format: ddd:hh24:mi-ddd:hh24:mi
   * The default is a 30-minute window selected at random from an 8-hour block of time for each Amazon Web Services Region, occurring on a random day of the week.
   * Valid Days: Mon, Tue, Wed, Thu, Fri, Sat, Sun.
   * Constraints: Minimum 30-minute window.
   *
   * @schema DbInstanceSpec#preferredMaintenanceWindow
   */
  readonly preferredMaintenanceWindow?: string;

  /**
   * The number of CPU cores and the number of threads per core for the DB instance class of the DB instance.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#processorFeatures
   */
  readonly processorFeatures?: DbInstanceSpecProcessorFeatures[];

  /**
   * A value that specifies the order in which an Aurora Replica is promoted to the primary instance after a failure of the existing primary instance. For more information, see Fault Tolerance for an Aurora DB Cluster (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html#Aurora.Managing.FaultTolerance) in the Amazon Aurora User Guide.
   * This setting doesn't apply to RDS Custom.
   * Default: 1
   * Valid Values: 0 - 15
   *
   * @schema DbInstanceSpec#promotionTier
   */
  readonly promotionTier?: number;

  /**
   * A value that indicates whether the DB instance is publicly accessible.
   * When the DB instance is publicly accessible, its DNS endpoint resolves to the private IP address from within the DB instance's VPC, and to the public IP address from outside of the DB instance's VPC. Access to the DB instance is ultimately controlled by the security group it uses, and that public access is not permitted if the security group assigned to the DB instance doesn't permit it.
   * When the DB instance isn't publicly accessible, it is an internal DB instance with a DNS name that resolves to a private IP address.
   * Default: The default behavior varies depending on whether DBSubnetGroupName is specified.
   * If DBSubnetGroupName isn't specified, and PubliclyAccessible isn't specified, the following applies:
   * * If the default VPC in the target region doesn’t have an Internet gateway    attached to it, the DB instance is private.
   * * If the default VPC in the target region has an Internet gateway attached    to it, the DB instance is public.
   * If DBSubnetGroupName is specified, and PubliclyAccessible isn't specified, the following applies:
   * * If the subnets are part of a VPC that doesn’t have an Internet gateway    attached to it, the DB instance is private.
   * * If the subnets are part of a VPC that has an Internet gateway attached    to it, the DB instance is public.
   *
   * @schema DbInstanceSpec#publiclyAccessible
   */
  readonly publiclyAccessible?: boolean;

  /**
   * A value that indicates whether the DB instance is encrypted. By default, it isn't encrypted.
   * For RDS Custom Oracle instances, either set this parameter to true or leave it unset. If you set this parameter to false, RDS reports an error.
   * Amazon Aurora
   * Not applicable. The encryption for DB instances is managed by the DB cluster.
   *
   * @schema DbInstanceSpec#storageEncrypted
   */
  readonly storageEncrypted?: boolean;

  /**
   * Specifies the storage type to be associated with the DB instance.
   * Valid values: standard | gp2 | io1
   * If you specify io1, you must also include a value for the Iops parameter.
   * Default: io1 if the Iops parameter is specified, otherwise gp2
   *
   * @schema DbInstanceSpec#storageType
   */
  readonly storageType?: string;

  /**
   * Tags to assign to the DB instance.
   *
   * @schema DbInstanceSpec#tags
   */
  readonly tags?: DbInstanceSpecTags[];

  /**
   * The ARN from the key store with which to associate the instance for TDE encryption.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#tdeCredentialARN
   */
  readonly tdeCredentialArn?: string;

  /**
   * The password for the given ARN from the key store in order to access the device.
   * This setting doesn't apply to RDS Custom.
   *
   * @schema DbInstanceSpec#tdeCredentialPassword
   */
  readonly tdeCredentialPassword?: string;

  /**
   * The time zone of the DB instance. The time zone parameter is currently supported only by Microsoft SQL Server (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html#SQLServer.Concepts.General.TimeZone).
   *
   * @schema DbInstanceSpec#timezone
   */
  readonly timezone?: string;

  /**
   * A list of Amazon EC2 VPC security groups to associate with this DB instance.
   * Amazon Aurora
   * Not applicable. The associated list of EC2 VPC security groups is managed by the DB cluster.
   * Default: The default EC2 VPC security group for the DB subnet group's VPC.
   *
   * @schema DbInstanceSpec#vpcSecurityGroupIDs
   */
  readonly vpcSecurityGroupIDs?: string[];

}

/**
 * Converts an object of type 'DbInstanceSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DbInstanceSpec(obj: DbInstanceSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'allocatedStorage': obj.allocatedStorage,
    'autoMinorVersionUpgrade': obj.autoMinorVersionUpgrade,
    'availabilityZone': obj.availabilityZone,
    'backupRetentionPeriod': obj.backupRetentionPeriod,
    'characterSetName': obj.characterSetName,
    'copyTagsToSnapshot': obj.copyTagsToSnapshot,
    'customIAMInstanceProfile': obj.customIamInstanceProfile,
    'dbClusterIdentifier': obj.dbClusterIdentifier,
    'dbInstanceClass': obj.dbInstanceClass,
    'dbInstanceIdentifier': obj.dbInstanceIdentifier,
    'dbName': obj.dbName,
    'dbParameterGroupName': obj.dbParameterGroupName,
    'dbSecurityGroups': obj.dbSecurityGroups?.map(y => y),
    'dbSubnetGroupName': obj.dbSubnetGroupName,
    'deletionProtection': obj.deletionProtection,
    'domain': obj.domain,
    'domainIAMRoleName': obj.domainIamRoleName,
    'enableCloudwatchLogsExports': obj.enableCloudwatchLogsExports?.map(y => y),
    'enableCustomerOwnedIP': obj.enableCustomerOwnedIp,
    'enableIAMDatabaseAuthentication': obj.enableIamDatabaseAuthentication,
    'engine': obj.engine,
    'engineVersion': obj.engineVersion,
    'iops': obj.iops,
    'kmsKeyID': obj.kmsKeyId,
    'kmsKeyRef': toJson_DbInstanceSpecKmsKeyRef(obj.kmsKeyRef),
    'licenseModel': obj.licenseModel,
    'masterUserPassword': toJson_DbInstanceSpecMasterUserPassword(obj.masterUserPassword),
    'masterUsername': obj.masterUsername,
    'maxAllocatedStorage': obj.maxAllocatedStorage,
    'monitoringInterval': obj.monitoringInterval,
    'monitoringRoleARN': obj.monitoringRoleArn,
    'multiAZ': obj.multiAz,
    'ncharCharacterSetName': obj.ncharCharacterSetName,
    'optionGroupName': obj.optionGroupName,
    'performanceInsightsEnabled': obj.performanceInsightsEnabled,
    'performanceInsightsKMSKeyID': obj.performanceInsightsKmsKeyId,
    'performanceInsightsRetentionPeriod': obj.performanceInsightsRetentionPeriod,
    'port': obj.port,
    'preferredBackupWindow': obj.preferredBackupWindow,
    'preferredMaintenanceWindow': obj.preferredMaintenanceWindow,
    'processorFeatures': obj.processorFeatures?.map(y => toJson_DbInstanceSpecProcessorFeatures(y)),
    'promotionTier': obj.promotionTier,
    'publiclyAccessible': obj.publiclyAccessible,
    'storageEncrypted': obj.storageEncrypted,
    'storageType': obj.storageType,
    'tags': obj.tags?.map(y => toJson_DbInstanceSpecTags(y)),
    'tdeCredentialARN': obj.tdeCredentialArn,
    'tdeCredentialPassword': obj.tdeCredentialPassword,
    'timezone': obj.timezone,
    'vpcSecurityGroupIDs': obj.vpcSecurityGroupIDs?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference type to provide more user friendly syntax for references using 'from' field Ex: APIIDRef:   from:     name: my-api
 *
 * @schema DbInstanceSpecKmsKeyRef
 */
export interface DbInstanceSpecKmsKeyRef {
  /**
   * AWSResourceReference provides all the values necessary to reference another k8s resource for finding the identifier(Id/ARN/Name)
   *
   * @schema DbInstanceSpecKmsKeyRef#from
   */
  readonly from?: DbInstanceSpecKmsKeyRefFrom;

}

/**
 * Converts an object of type 'DbInstanceSpecKmsKeyRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DbInstanceSpecKmsKeyRef(obj: DbInstanceSpecKmsKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'from': toJson_DbInstanceSpecKmsKeyRefFrom(obj.from),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * The password for the master user. The password can include any printable ASCII character except "/", """, or "@".
 * Amazon Aurora
 * Not applicable. The password for the master user is managed by the DB cluster.
 * MariaDB
 * Constraints: Must contain from 8 to 41 characters.
 * Microsoft SQL Server
 * Constraints: Must contain from 8 to 128 characters.
 * MySQL
 * Constraints: Must contain from 8 to 41 characters.
 * Oracle
 * Constraints: Must contain from 8 to 30 characters.
 * PostgreSQL
 * Constraints: Must contain from 8 to 128 characters.
 *
 * @schema DbInstanceSpecMasterUserPassword
 */
export interface DbInstanceSpecMasterUserPassword {
  /**
   * Key is the key within the secret
   *
   * @schema DbInstanceSpecMasterUserPassword#key
   */
  readonly key: string;

  /**
   * Name is unique within a namespace to reference a secret resource.
   *
   * @schema DbInstanceSpecMasterUserPassword#name
   */
  readonly name?: string;

  /**
   * Namespace defines the space within which the secret name must be unique.
   *
   * @schema DbInstanceSpecMasterUserPassword#namespace
   */
  readonly namespace?: string;

}

/**
 * Converts an object of type 'DbInstanceSpecMasterUserPassword' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DbInstanceSpecMasterUserPassword(obj: DbInstanceSpecMasterUserPassword | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Contains the processor features of a DB instance class.
 * To specify the number of CPU cores, use the coreCount feature name for the Name parameter. To specify the number of threads per core, use the threadsPerCore feature name for the Name parameter.
 * You can set the processor features of the DB instance class for a DB instance when you call one of the following actions:
 * * CreateDBInstance
 * * ModifyDBInstance
 * * RestoreDBInstanceFromDBSnapshot
 * * RestoreDBInstanceFromS3
 * * RestoreDBInstanceToPointInTime
 * You can view the valid processor values for a particular instance class by calling the DescribeOrderableDBInstanceOptions action and specifying the instance class for the DBInstanceClass parameter.
 * In addition, you can use the following actions for DB instance class processor information:
 * * DescribeDBInstances
 * * DescribeDBSnapshots
 * * DescribeValidDBInstanceModifications
 * If you call DescribeDBInstances, ProcessorFeature returns non-null values only if the following conditions are met:
 * * You are accessing an Oracle DB instance.
 * * Your Oracle DB instance class supports configuring the number of CPU    cores and threads per core.
 * * The current number CPU cores and threads is set to a non-default value.
 * For more information, see Configuring the Processor of the DB Instance Class (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#USER_ConfigureProcessor) in the Amazon RDS User Guide.
 *
 * @schema DbInstanceSpecProcessorFeatures
 */
export interface DbInstanceSpecProcessorFeatures {
  /**
   * @schema DbInstanceSpecProcessorFeatures#name
   */
  readonly name?: string;

  /**
   * @schema DbInstanceSpecProcessorFeatures#value
   */
  readonly value?: string;

}

/**
 * Converts an object of type 'DbInstanceSpecProcessorFeatures' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DbInstanceSpecProcessorFeatures(obj: DbInstanceSpecProcessorFeatures | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'value': obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Metadata assigned to an Amazon RDS resource consisting of a key-value pair.
 *
 * @schema DbInstanceSpecTags
 */
export interface DbInstanceSpecTags {
  /**
   * @schema DbInstanceSpecTags#key
   */
  readonly key?: string;

  /**
   * @schema DbInstanceSpecTags#value
   */
  readonly value?: string;

}

/**
 * Converts an object of type 'DbInstanceSpecTags' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DbInstanceSpecTags(obj: DbInstanceSpecTags | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'value': obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * AWSResourceReference provides all the values necessary to reference another k8s resource for finding the identifier(Id/ARN/Name)
 *
 * @schema DbInstanceSpecKmsKeyRefFrom
 */
export interface DbInstanceSpecKmsKeyRefFrom {
  /**
   * @schema DbInstanceSpecKmsKeyRefFrom#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'DbInstanceSpecKmsKeyRefFrom' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_DbInstanceSpecKmsKeyRefFrom(obj: DbInstanceSpecKmsKeyRefFrom | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

